# Generated by Django 6.0.3 on 2026-03-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contact", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("tech_stack", models.CharField(max_length=200)),
                (
                    "total_experience",
                    models.DecimalField(decimal_places=1, max_digits=4),
                ),
            ],
        ),
    ]
