# Generated by Django 6.0.3 on 2026-03-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institute_name", models.CharField(max_length=150)),
                ("contact_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("course_offered", models.CharField(max_length=100)),
                ("tech_stack", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("address", models.TextField()),
            ],
        ),
    ]
